name = "ai-gateway"
main = "src/index.ts"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

# KV namespace
[[kv_namespaces]]
binding = "KV"
id = "f8f174699b4b43b3ae29594484921b07"

# Admin credentials and OpenCode mirrors (synced from Dashboard)
[vars]
ADMIN_USERNAME = "admin"
OPENCODE_MIRRORS_URL = "https://opencode.ai.cmliussss.net/zen/v1\nhttps://opencode.fastly.cmliussss.net/zen/v1\nhttps://opencode.gcore.cmliussss.net/zen/v1"
